# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0003_delete_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='remaining',
            field=models.FloatField(default=0),
        ),
    ]
